### ISSUE TITLE
Resolve Sequence.Flow issue for on-push array to be on a single line 

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#10]
Details in this YAMLDotNet: issue: https://github.com/aaubry/YamlDotNet/issues/9

**Comment by samsmithnz** [comment]
Resolved - we used the complex version of triggers instead. 

e.g. instead of: 
```
on: [push]
```
We use:
```
on:
  push:
    branches:
    - master
```
