### ISSUE TITLE
Extra null steps appearing

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#101]
Extra null steps appearing, (see the extra -) why?
```
    steps:
    - uses: actions/checkout@v1
    - #: 'Note that "AZURE_SP" secret is required to be setup and added into GitHub Secrets: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets'
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - 
    - 
    - name: Download the build artifacts
      uses: actions/download-artifact@v1.0.0
      with:
        name: drop
```
