### ISSUE TITLE
Powershell when targettype is "FilePath" is not working

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#113]
Currently:
```
    - task: PowerShell@2
      displayName: 'PowerShell test task'
      inputs:
        targetType: FilePath
        filePath: MyProject/BuildVersion.ps1
        arguments: -ProjectFile "MyProject/MyProject.Web/MyProject.Web.csproj"
```

Just returns:
```
- name: PowerShell test task
  shell: powershell
```

but should return:

```
- name: PowerShell test task
  run: MyProject/BuildVersion.ps1 -ProjectFile ""MyProject/MyProject.Web/MyProject.Web.csproj""
  shell: powershell
```
