### ISSUE TITLE
move package to semantic versioning

### ISSUE THREAD

**Issue by f2calv** [samsmithnz/AzurePipelinesToGitHubActionsConverter#126]
The defacto standard for NuGet package versioning is Semantic Versioning, i.e. 1.2.3 (Major.Minor.Patch) your package https://www.nuget.org/packages/AzurePipelinesToGitHubActionsConverter.Core/ doesn't use this style.

![image](https://user-images.githubusercontent.com/16097639/88426105-d5246a00-cdf0-11ea-9446-03ccc1e6302c.png)

It would be better to join other listings and use SemVer.

**Comment by samsmithnz** [comment]
Good call. I did this so I could continuously push versions without having to worry too much about updating the package version. I recognize I should instead be adding a preview flag, so that only non-preview versions are 1.2.3, and the rest are something like 1.2.3-preview.[revision]

**Comment by samsmithnz** [comment]
@f2calv, Any experience with auto updating the patch version? You've probably seen my PowerShell that is doing this, but ideally you want the autoupdated version to also be updated in the source, and that is where I get stuck and have this solution to generate a revision and keep major.minor.patch in the source.

This came up yesterday, as I had a bug in my script where it wasn't adding a leading 0, causing some newer packages to not be the newest. I resolved it with a ToString("00000"), but curious if there is a better way to address this issue and the problem I'm just missing.

![image](https://user-images.githubusercontent.com/8389039/90631300-7fc15a00-e1f0-11ea-85bf-f557fd59bbe9.png)

**Comment by f2calv** [comment]
I haven't got a good answer to be honest, for me (at my 'hobby' stage of NuGet publication) I'm not so bothered about having the semver inside the binary (what would I ever do with it if it were there?).

I rely on `dotnet pack` to handle the versioning when it creates the nupkg for me. [In my pipline](https://github.com/f2calv/yamlizr/blob/master/.azure-pipelines/azure-pipelines.yml) every time I run my publish job from master I'm accept it's a new patch version and the pipeline increments the patch accordingly. If I want to increment the Major/Minor version I just edit the pipeline...

```yaml
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - stage: Publish
    jobs:
    - job: PublishJob
      variables:
        Version.Major: 1
        Version.Minor: 0
        Version.PackageMajorMinor: $(Version.Minor).$(Version.Major)-$(SolutionName)
        Version.Revision: $[counter(variables['Version.PackageMajorMinor'], 0)]
        PackageVersion: $(Version.Major).$(Version.Minor).$(Version.Revision)
      steps:
      - template: templates/steps.dotnet.publish.nuget-v2.yml@sharedTemplates
        parameters:
          packagesToPack: '*.csproj'
          NuGetFeedUrl: https://api.nuget.org/v3/index.json
          NuGetFeedAPIKey: $(f2calvNuGet)
```
