### ISSUE TITLE
Add support for DownloadPipelineArtifact@2 task

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#138]
This is is likely very similar to the the DownloadBuildArtifacts@0 task that we do support.

```
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'WebDeploy'
                  targetPath: '$(Pipeline.Workspace)'
```
