### ISSUE TITLE
Add support for condition insertion

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#141]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops

```
variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: # only works if you have a master branch
    stageName: prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo ${{variables.stageName}}
```
