### ISSUE TITLE
Add support for AzureCLI and AzurePowerShell tasks

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#172]
Azure CLI example:
```
            - task: AzureCLI@2
              displayName: Azure CLI
              inputs:
                azureSubscription: <Name of the Azure Resource Manager service connection>
                scriptType: ps
                scriptLocation: inlineScript
                inlineScript: |
                  az --version
                  az account show
```

Azure PowerShell example:
```
            - task: AzurePowerShell@4
              inputs:
                #azureSubscription: Required. Name of Azure Resource Manager service connection
                #scriptType: 'FilePath' # Optional. Options: filePath, inlineScript
                #scriptPath: # Optional
                #inline: '# You can write your Azure PowerShell scripts inline here. # You can also pass predefined and custom variables to this script using arguments' # Optional
                #scriptArguments: # Optional
                #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
                #failOnStandardError: false # Optional
                #azurePowerShellVersion: 'OtherVersion' # Required. Options: latestVersion, otherVersion
                #preferredAzurePowerShellVersion: # Required when azurePowerShellVersion == OtherVersion

```
