### ISSUE TITLE
Fix stage dependsOn - and convert correctly in stages 

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#200]
This: 
```
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
  
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: DotNetCoreCLI@2
```

Should transfer to something like (Note the needs):
```
jobs:
  Build_Stage_Build:
    name: Build job
    runs-on: ${{ env.vmImage }}
    steps:
    - uses: actions/checkout@v2
  Deploy_Stage_Deploy:
    runs-on: ${{ env.vmImage }}
    needs: Build_Stage_Build
    steps:
    - uses: actions/checkout@v2
```

However, currently this:
```
stages:
  - stage: Deployment
    displayName: Deployment
    #condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    dependsOn: BuildAndTest
    jobs:
      - job: DeployToSlots
        displayName: 'Deploy web service'
        pool:
          vmImage: windows-latest       
        steps:
        - task: DownloadBuildArtifacts@0
          displayName: 'Download the build artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(build.artifactstagingdirectory)'
```

translates to: (it's missing the needs "BuildAndTest")
```
jobs:
  Deployment_Stage_DeployToSlots:
    name: Deploy web service
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download the build artifacts
      uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{ github.workspace }}
```
