### ISSUE TITLE
Bug: For some reason I can't use a variable for "runs-on"

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#21]
For example, this doesn't work

```
name: CI 

on: [push]
env:
  vmImage: ubuntu-latest
jobs:
  Build:
    runs-on: $vmImage
    steps:
    - uses: actions/checkout@v1
```
