### ISSUE TITLE
In same cases, the checkout: self task can duplicate multiple times

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#218]
For example:

```
jobs:
- job: Build
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    submodules: true
```

Becomes:
```
on:
  push:
    branches:
    - master
jobs:
  Build:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
```
