### ISSUE TITLE
Add Support for Terraform tasks

### ISSUE THREAD

**Issue by JFolberth** [samsmithnz/AzurePipelinesToGitHubActionsConverter#226]
**Is your feature request related to a problem? Please describe.**
When converting Terraform tasks throws an error that they are not supported yet.

**Additional context**
Both TerraformTaskV1 and TerraformInstaller not supported.

**Comment by samsmithnz** [comment]
Can you help me and link to the Azure DevOps tasks you are referring to? They aren't showing up obviously on the front page of my search results. A Sample/Example would be helpful too!

**Comment by f2calv** [comment]
These two tasks are non-standard tasks which you have to manually install into your azdo organisation;

https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks

**Comment by JFolberth** [comment]
No problem!
```

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 0.14.2
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : init'
      inputs:
        command: init
        workingDirectory: tf/env/dev
        backendServiceArm: YAML Template Examples - Dev
        backendAzureRmResourceGroupName: rg-terraformState-dev-eus
        backendAzureRmStorageAccountName: sadummystroage
        backendAzureRmContainerName: terraform-state
        backendAzureRmKey: terraformStorageExample.tfstate
```

The command will be different depending what you'd like to do in Terraform but there's an example of the Terraform installer and the Terraform Task

**Comment by JFolberth** [comment]
No problem!
```

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 0.14.2
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : init'
      inputs:
        command: init
        workingDirectory: tf/env/dev
        backendServiceArm: YAML Template Examples - Dev
        backendAzureRmResourceGroupName: rg-terraformState-dev-eus
        backendAzureRmStorageAccountName: #
        backendAzureRmContainerName: terraform-state
        backendAzureRmKey: terraformStorageExample.tfstate
```

The command will be different depending what you'd like to do in Terraform but there's an example of the Terraform installer and the Terraform Task
