### ISSUE TITLE
Add support for InlinePowershell@1 task (4 failures)

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#264]
- 4 failures 28-Feb-2021
```
  - task: InlinePowershell@1                
    displayName: 'old Powershell task'
    inputs:
      Script: |
        Write-Host "Hello World"
```
