### ISSUE TITLE
.NET conversion bug

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#270]
When converting a .NET task with multiple lines, it combines all the lines together:

```
        - task: DotNetCoreCLI@2
          displayName: 'Publish dotnet projects'
          inputs:
            command: publish
            publishWebProjects: false
            projects: |
             src/Project.Service/Project.Service.csproj
             src/Project.Web/Project.Web.csproj
            arguments: '--configuration Release --output $(build.artifactstagingdirectory) --runtime win-x64'
            zipAfterPublish: true
```
Currently, this produces:
```
    - name: Publish dotnet web projects
      run: dotnet publish src/Project.Service/Project.Service.csprojsrc/Project.Web/Project.Web.csproj --configuration Release --output ${{ github.workspace }} --runtime win-x64

```
But i think it should create:
```
    - name: Publish dotnet web projects
      run: |
        dotnet publish src/Project.Service/Project.Service.csproj --configuration Release --output ${{ github.workspace }} --runtime win-x64
        dotnet publish  src/Project.Web/Project.Web.csproj --configuration Release --output ${{ github.workspace }} --runtime win-x64

```
