### ISSUE TITLE
Add support for Octopus conversions

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#319]
There are two tasks (pack + push), and GitHub requires an additional installation step

- [x] convert pack task
- [x] convert push task
- [x] add installation task whenever either is used.

Azure DevOps:
```

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-pack.OctopusPack@4
  displayName: 'Package OctopusSamples.OctoPetShop.Database'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.Database
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.Database\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-pack.OctopusPack@4
  displayName: 'Package OctopusSamples.OctoPetShop.Web'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.Web
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.Web\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-pack.OctopusPack@4
  displayName: 'Package OctopusSamples.OctoPetShop.ProductService'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.ProductService
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.ProductService\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-pack.OctopusPack@4
  displayName: 'Package OctopusSamples.Octopetshop.ShoppingCartService'
  inputs:
    PackageId: OctopusSamples.OctoPetShop.ShoppingCartService
    PackageFormat: Zip
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)\output\OctoPetShop.ShoppingCartService\'
    OutputPath: '$(Build.SourcesDirectory)\output'

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-push.OctopusPush@4
  displayName: 'Push Packages to Octopus'
  inputs:
    OctoConnectedServiceName: OctopusWebinars
    Space: 'Spaces-222'
    Package: '$(Build.SourcesDirectory)/output/*.zip'
```
GitHub Actions:
```
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octocli@v1
      with:
        version: 7.4.2
    - name: Package OctoPetShopDatabase
      run: |
        octo pack --id="OctoPetShop.Database" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Database" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package OctoPetShopWeb
      run: |
        octo pack --id="OctoPetShop.Web" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Web" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package OctoPetShopProductService
      run: |
        octo pack --id="OctoPetShop.ProductService" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.ProductService" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package OctoPetShopShoppingCartService
      run: |
        octo pack --id="OctoPetShop.ShoppingCartService" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetshop.ShoppingCartService" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Push OctoPetShop Database
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoPetShop.Database.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
    - name: Push OctoPetShop Web
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoPetShop.Web.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
    - name: Push OctoPetShop ProductService
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoPetShop.ProductService.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
    - name: Push OctoPetShop ShoppingCartService
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoPetShop.ShoppingCartService.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
```
