### ISSUE TITLE
BUG: using Parameters, templates, or condition insertion variables in YAML throws exceptions

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#61]
using:
- [x] Parameters
- [x] templates
- [x] condition insertion variables in YAML throws exceptions

**Comment by samsmithnz** [comment]
This currently fails due to the conditional variables:

```
stages:
- stage: DeployPR
  displayName: 'Deploy PR Stage'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), ne(variables['System.PullRequest.PullRequestId'], 'Null'))
  dependsOn: Build
  variables:
    ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      prId: "$(System.PullRequest.PullRequestId)"
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      prId: '000'
    prUC: "PR$(prId)"
    prLC: "pr$(prId)"
```
