### ISSUE TITLE
variable groups not currently supported

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#62]
**Example**:
```
variables:
- group: 'my group name'
```
**Resolution**:
need to support all variable types

- [x] 1. Regular/list based (currently support):

```
variables:
  configuration: debug
  platform: x64
```

- [x] 2. Irregular/object based:

```
variables:
# a regular variable
- name: myvariable
  value: myvalue
# a variable group
- group: myvariablegroup
# a reference to a variable template
- template: myvariabletemplate.yml
```
e.g.
```
variables: 
- group: 'my-var-group' # variable group
- name: 'devopsAccount' # new variable defined in YAML
  value: 'contoso'
- name: 'projectName' # new variable defined in YAML
  value: 'contosoads'
```
