### ISSUE TITLE
Many comments are removed as part of serialization

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#79]
For example: 

```
variables:
  #PR code 
  prId: '000'
  prName: ""PR$(prId)""
```

serializes without the comment, to:
```
env:
  prId: 000
  prName: PR${{ env.prId }}
```

This seems to be related to https://github.com/aaubry/YamlDotNet/issues/451
