### ISSUE TITLE
MSBuild task is showing escaped newline characters instead of actual newlines

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#81]
This YAML processes the msbuild with escaped newline characters, instead of real new lines:
```
# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```

Result:
```

#Note: Needs to be installed from marketplace: https://github.com/warrenbuckley/Setup-Nuget
on:
  push:
    branches:
    - master
env:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - #: 'Note: Needs to be installed from marketplace: https://github.com/warrenbuckley/Setup-Nuget'
      uses: warrenbuckley/Setup-Nuget@v1
    - run: nuget  ${{ env.solution }}
      shell: powershell
    - run: " |\n    $msBuildExe = \"C:\\Program Files(x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\msbuild.exe\"\n    $targetSolution = \"${{ env.solution }}\"\n    #Note that the `\" is an escape character sequence to quote strings, and `& is needed to start the command\n    $command = \"`& `\"$msBuildExe`\" `\"$targetSolution`\" \n    Write - Host \"$command\"\n    Invoke - Expression $command"
      shell: powershell
    - run: |
            $vsTestConsoleExe = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
            $targetTestDll = ""
            $testRunSettings = " / Settings:`"`" "
            $parameters = "-- "    #Note that the `" is an escape character sequence to quote strings, and `& is needed to start the command
            $command = "`& `"$vsTestConsoleExe`" `"$targetTestDll`" $testRunSettings $parameters "
            Write - Host "$command"
            Invoke - Expression $command
      shell: powershell
                    
```
