### ISSUE TITLE
Resolve issues with Docker@2 task

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#84]
Need to handle:
- [x] build
- [x] push
- [x] build and push
- [x] login
- [x] logout

```
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '{{ dockerfilePath }}'
        tags: |
          $(tag)
```
