### ISSUE TITLE
Resolve unexpected null reference exception

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#88]
This should work, but throws an error:

Unexpected error: System.NullReferenceException: Object reference not set to an instance of an object.
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.StepsProcessing.GetStepInput(Step step, String name)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.StepsProcessing.CreatePublishBuildArtifactsStep(Step step)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.StepsProcessing.ProcessStep(Step step)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.PipelineProcessing`2.ProcessSteps(Step[] steps, Boolean addCheckoutStep)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.PipelineProcessing`2.ProcessPipeline(AzurePipelinesRoot`2 azurePipeline, String[] simpleTrigger, Trigger complexTrigger, Dictionary`2 simpleVariables, Variables[] complexVariables)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.Conversion.ConvertAzurePipelineToGitHubAction(String input)
   at PipelinesToActionsWeb.Controllers.HomeController.ProcessConversion(String input) in D:\a\AzurePipelinesToGitHubActionsConverterWeb\AzurePipelinesToGitHubActionsConverterWeb\PipelinesToActions\PipelinesToActions\Controllers\HomeController.cs:line 44
                    

```
# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
```
